# Generated by Django 2.1.5 on 2019-02-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('username', 'ticket')},
        ),
    ]
